language: r
pandoc_version: 1.17.2
cache: packages

branches:
  only: master

script:
  - Rscript -e 'servr:::knit_maybe(c(".", "src"), c(".", "docs"), "build.R", "jekyll")'

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
target_branch: gh-pages
